#NOTE: 07.03.2020 17:29:24
BAT_ADC_CHANNEL,-1
BAT_A_PER_V,36.367515563964844
BAT_CAPACITY,-1.0
BAT_CNT_V_CURR,0.0008056640508584678
BAT_CNT_V_VOLT,0.0008056640508584678
BAT_CRIT_THR,0.07000000029802322
BAT_EMERGEN_THR,0.05000000074505806
BAT_LOW_THR,0.15000000596046448
BAT_N_CELLS,7
BAT_R_INTERNAL,-1.0
BAT_SOURCE,0
BAT_V_CHARGED,4.050000190734863
BAT_V_DIV,18.100000381469727
BAT_V_EMPTY,3.5
BAT_V_LOAD_DROP,0.30000001192092896
BAT_V_OFFS_CURR,0.0
CAL_ACC0_EN,1
CAL_ACC0_ID,3866634
CAL_ACC0_XOFF,0.020027637481689453
CAL_ACC0_XSCALE,1.0067360401153564
CAL_ACC0_YOFF,0.1117701530456543
CAL_ACC0_YSCALE,1.001807689666748
CAL_ACC0_ZOFF,-0.12737274169921875
CAL_ACC0_ZSCALE,0.983260452747345
CAL_ACC1_EN,1
CAL_ACC1_ID,4260618
CAL_ACC1_XOFF,0.5694975852966309
CAL_ACC1_XSCALE,0.9905802607536316
CAL_ACC1_YOFF,-0.1264176368713379
CAL_ACC1_YSCALE,0.9783436059951782
CAL_ACC1_ZOFF,0.16154098510742188
CAL_ACC1_ZSCALE,0.9732335805892944
CAL_ACC_PRIME,3866634
CAL_AIR_CMODEL,0
CAL_AIR_TUBED_MM,1.5
CAL_AIR_TUBELEN,0.20000000298023224
CAL_BARO_PRIME,0
CAL_GYRO0_EN,1
CAL_GYRO0_ID,3932170
CAL_GYRO0_XOFF,0.050267625600099564
CAL_GYRO0_XSCALE,1.0
CAL_GYRO0_YOFF,-0.01888122782111168
CAL_GYRO0_YSCALE,1.0
CAL_GYRO0_ZOFF,-0.009226853027939796
CAL_GYRO0_ZSCALE,1.0
CAL_GYRO1_EN,1
CAL_GYRO1_ID,4325898
CAL_GYRO1_XOFF,-0.00023796272580511868
CAL_GYRO1_XSCALE,1.0
CAL_GYRO1_YOFF,0.0026812779251486063
CAL_GYRO1_YSCALE,1.0
CAL_GYRO1_ZOFF,-0.0011039567179977894
CAL_GYRO1_ZSCALE,1.0
CAL_GYRO_PRIME,3932170
CAL_MAG0_EN,1
CAL_MAG0_ID,396809
CAL_MAG0_ROT,0
CAL_MAG0_XOFF,-6.276679039001465
CAL_MAG0_XSCALE,0.055507250130176544
CAL_MAG0_YOFF,-1.4232144355773926
CAL_MAG0_YSCALE,0.13019970059394836
CAL_MAG0_ZOFF,0.83941251039505
CAL_MAG0_ZSCALE,0.17779852449893951
CAL_MAG1_EN,1
CAL_MAG1_ID,396825
CAL_MAG1_ROT,-1
CAL_MAG1_XOFF,0.01710902713239193
CAL_MAG1_XSCALE,0.9750320315361023
CAL_MAG1_YOFF,0.0200135949999094
CAL_MAG1_YSCALE,1.0141931772232056
CAL_MAG1_ZOFF,0.0709884911775589
CAL_MAG1_ZSCALE,0.9232190251350403
CAL_MAG2_ID,0
CAL_MAG2_ROT,-1
CAL_MAG3_ID,0
CAL_MAG3_ROT,-1
CAL_MAG_PRIME,396809
CAL_MAG_SIDES,63
CAM_CAP_FBACK,0
CBRK_AIRSPD_CHK,162128
CBRK_BUZZER,782097
CBRK_ENGINEFAIL,284953
CBRK_FLIGHTTERM,121212
CBRK_GPSFAIL,240024
CBRK_IO_SAFETY,22027
CBRK_SUPPLY_CHK,894281
CBRK_USB_CHK,197848
CBRK_VELPOSERR,201607
COM_ARM_AUTH,256010
COM_ARM_CHK_ESCS,1
COM_ARM_EKF_AB,0.0017300000181421638
COM_ARM_EKF_GB,0.0008699999889358878
COM_ARM_EKF_HGT,1.0
COM_ARM_EKF_POS,0.5
COM_ARM_EKF_VEL,0.5
COM_ARM_EKF_YAW,0.5
COM_ARM_IMU_ACC,0.699999988079071
COM_ARM_IMU_GYR,0.25
COM_ARM_MIS_REQ,0
COM_ARM_SWISBTN,0
COM_ARM_WO_GPS,1
COM_ASPD_FS_ACT,0
COM_ASPD_FS_DLY,0
COM_ASPD_STALL,10.0
COM_DISARM_LAND,2.0
COM_DISARM_PRFLT,10.0
COM_DL_LOSS_T,10
COM_EF_C2T,5.0
COM_EF_THROT,0.5
COM_EF_TIME,10.0
COM_FLIGHT_UUID,0
COM_FLTMODE1,0
COM_FLTMODE2,-1
COM_FLTMODE3,-1
COM_FLTMODE4,-1
COM_FLTMODE5,-1
COM_FLTMODE6,-1
COM_FLT_PROFILE,0
COM_HLDL_LOSS_T,120
COM_HLDL_REG_T,0
COM_HOME_H_T,5.0
COM_HOME_V_T,10.0
COM_LOW_BAT_ACT,0
COM_OA_BOOT_T,100
COM_OBL_ACT,0
COM_OBL_RC_ACT,0
COM_OBS_AVOID,0
COM_OF_LOSS_T,0.0
COM_POSCTL_NAVL,0
COM_POS_FS_DELAY,1
COM_POS_FS_EPH,5.0
COM_POS_FS_EPV,10.0
COM_POS_FS_GAIN,10
COM_POS_FS_PROB,30
COM_PREARM_MODE,1
COM_RC_ARM_HYST,1000
COM_RC_IN_MODE,0
COM_RC_LOSS_T,0.5
COM_RC_OVERRIDE,1
COM_RC_STICK_OV,12.0
COM_TAKEOFF_ACT,0
COM_TAS_FS_INNOV,1.0
COM_TAS_FS_INTEG,-1.0
COM_TAS_FS_T1,3
COM_TAS_FS_T2,100
COM_VEL_FS_EVH,1.0
DSHOT_CONFIG,0
DSHOT_TEL_CFG,0
EKF2_ABIAS_INIT,0.20000000298023224
EKF2_ABL_ACCLIM,25.0
EKF2_ABL_GYRLIM,3.0
EKF2_ABL_LIM,0.4000000059604645
EKF2_ABL_TAU,0.5
EKF2_ACC_B_NOISE,0.003000000026077032
EKF2_ACC_NOISE,0.3499999940395355
EKF2_AID_MASK,0
EKF2_ANGERR_INIT,0.009999999776482582
EKF2_ARSP_THR,0.0
EKF2_ASPD_MAX,20.0
EKF2_ASP_DELAY,100.0
EKF2_AVEL_DELAY,5.0
EKF2_BARO_DELAY,0.0
EKF2_BARO_GATE,5.0
EKF2_BARO_NOISE,2.0
EKF2_BCOEF_X,25.0
EKF2_BCOEF_Y,25.0
EKF2_BETA_GATE,5.0
EKF2_BETA_NOISE,0.30000001192092896
EKF2_DECL_TYPE,7
EKF2_DRAG_NOISE,2.5
EKF2_EAS_NOISE,1.399999976158142
EKF2_EVA_NOISE,0.05000000074505806
EKF2_EVP_GATE,5.0
EKF2_EVP_NOISE,0.10000000149011612
EKF2_EVV_GATE,3.0
EKF2_EVV_NOISE,0.10000000149011612
EKF2_EV_DELAY,175.0
EKF2_EV_NOISE_MD,0
EKF2_EV_POS_X,0.0
EKF2_EV_POS_Y,0.0
EKF2_EV_POS_Z,0.0
EKF2_FUSE_BETA,0
EKF2_GBIAS_INIT,0.009999999776482582
EKF2_GND_EFF_DZ,0.0
EKF2_GND_MAX_HGT,0.5
EKF2_GPS_CHECK,245
EKF2_GPS_DELAY,110.0
EKF2_GPS_MASK,0
EKF2_GPS_POS_X,0.0
EKF2_GPS_POS_Y,0.0
EKF2_GPS_POS_Z,0.0
EKF2_GPS_P_GATE,5.0
EKF2_GPS_P_NOISE,0.5
EKF2_GPS_TAU,10.0
EKF2_GPS_V_GATE,5.0
EKF2_GPS_V_NOISE,0.5
EKF2_GYR_B_NOISE,0.0010000000474974513
EKF2_GYR_NOISE,0.014999999664723873
EKF2_HDG_GATE,2.5999999046325684
EKF2_HEAD_NOISE,0.30000001192092896
EKF2_HGT_MODE,0
EKF2_IMU_POS_X,0.0
EKF2_IMU_POS_Y,0.0
EKF2_IMU_POS_Z,0.0
EKF2_MAGBIAS_ID,396809
EKF2_MAGBIAS_X,0.0
EKF2_MAGBIAS_Y,0.0
EKF2_MAGBIAS_Z,0.0
EKF2_MAGB_K,0.20000000298023224
EKF2_MAGB_VREF,2.499999993688107e-07
EKF2_MAG_ACCLIM,0.5
EKF2_MAG_B_NOISE,9.999999747378752e-05
EKF2_MAG_DECL,0.0
EKF2_MAG_DELAY,0.0
EKF2_MAG_E_NOISE,0.0010000000474974513
EKF2_MAG_GATE,3.0
EKF2_MAG_NOISE,0.05000000074505806
EKF2_MAG_TYPE,1
EKF2_MAG_YAWLIM,0.25
EKF2_MIN_OBS_DT,20
EKF2_MIN_RNG,0.10000000149011612
EKF2_MOVE_TEST,1.0
EKF2_NOAID_NOISE,10.0
EKF2_NOAID_TOUT,5000000
EKF2_OF_DELAY,5.0
EKF2_OF_GATE,3.0
EKF2_OF_N_MAX,0.5
EKF2_OF_N_MIN,0.15000000596046448
EKF2_OF_POS_X,0.0
EKF2_OF_POS_Y,0.0
EKF2_OF_POS_Z,0.0
EKF2_OF_QMIN,1
EKF2_PCOEF_XN,0.0
EKF2_PCOEF_XP,0.0
EKF2_PCOEF_YN,0.0
EKF2_PCOEF_YP,0.0
EKF2_PCOEF_Z,0.0
EKF2_REQ_EPH,3.0
EKF2_REQ_EPV,5.0
EKF2_REQ_GDOP,2.5
EKF2_REQ_GPS_H,10.0
EKF2_REQ_HDRIFT,0.10000000149011612
EKF2_REQ_NSATS,6
EKF2_REQ_SACC,0.5
EKF2_REQ_VDRIFT,0.20000000298023224
EKF2_RNG_AID,0
EKF2_RNG_A_HMAX,5.0
EKF2_RNG_A_IGATE,1.0
EKF2_RNG_A_VMAX,1.0
EKF2_RNG_DELAY,5.0
EKF2_RNG_GATE,5.0
EKF2_RNG_NOISE,0.10000000149011612
EKF2_RNG_PITCH,0.0
EKF2_RNG_POS_X,0.0
EKF2_RNG_POS_Y,0.0
EKF2_RNG_POS_Z,0.0
EKF2_RNG_SFE,0.05000000074505806
EKF2_TAS_GATE,3.0
EKF2_TAU_POS,0.25
EKF2_TAU_VEL,0.25
EKF2_TERR_GRAD,0.5
EKF2_TERR_NOISE,5.0
EKF2_WIND_NOISE,0.10000000149011612
EV_TSK_RC_LOSS,0
EV_TSK_STAT_DIS,0
FD_FAIL_P,60
FD_FAIL_P_TTRI,0.30000001192092896
FD_FAIL_R,60
FD_FAIL_R_TTRI,0.30000001192092896
FW_MAN_P_SC,1.0
FW_MAN_R_SC,1.0
FW_MAN_Y_SC,1.0
GF_ACTION,1
GF_ALTMODE,0
GF_COUNT,-1
GF_MAX_HOR_DIST,0.0
GF_MAX_VER_DIST,0.0
GF_SOURCE,0
GND_L1_DAMPING,0.75
GND_L1_DIST,10.0
GND_L1_PERIOD,10.0
GND_MAX_ANG,0.7853999733924866
GND_SPEED_D,3.0
GND_SPEED_I,0.0010000000474974513
GND_SPEED_IMAX,0.125
GND_SPEED_MAX,10.0
GND_SPEED_P,0.25
GND_SPEED_THR_SC,1.0
GND_SPEED_TRIM,3.0
GND_SP_CTRL_MODE,1
GND_THR_CRUISE,0.0
GND_THR_MAX,0.5
GND_THR_MIN,0.0
GND_WHEEL_BASE,2.0
GPS_1_CONFIG,201
GPS_2_CONFIG,0
GPS_DUMP_COMM,0
GPS_UBX_DYNMODEL,7
GPS_YAW_OFFSET,0.0
IMU_ACCEL_CUTOFF,30.0
IMU_GYRO_CUTOFF,30.0
IMU_GYRO_RATEMAX,0
ISBD_CONFIG,0
LED_RGB1_MAXBRT,31
LIGHT_EN_BLINKM,0
LND_FLIGHT_T_HI,0
LND_FLIGHT_T_LO,0
MAV_0_CONFIG,101
MAV_0_FORWARD,1
MAV_0_MODE,0
MAV_0_RATE,1200
MAV_1_CONFIG,0
MAV_2_CONFIG,0
MAV_COMP_ID,1
MAV_FWDEXTSP,1
MAV_HASH_CHK_EN,1
MAV_HB_FORW_EN,1
MAV_ODOM_LP,0
MAV_PROTO_VER,0
MAV_RADIO_ID,0
MAV_SYS_ID,1
MAV_TYPE,10
MAV_USEHILGPS,0
MC_AIRMODE,0
MIS_ALTMODE,1
MIS_DIST_1WP,900.0
MIS_DIST_WPS,900.0
MIS_LTRMIN_ALT,0.009999999776482582
MIS_MNT_YAW_CTL,0
MIS_TAKEOFF_ALT,0.009999999776482582
MIS_TAKEOFF_REQ,0
MIS_YAW_ERR,12.0
MIS_YAW_TMT,-1.0
MNT_MODE_IN,-1
MOT_ORDERING,0
MOT_SLEW_MAX,0.0
MPC_ACC_HOR,3.0
MPC_XY_CRUISE,5.0
NAV_ACC_RAD,0.5
NAV_AH_ALT,600.0
NAV_AH_LAT,-265847810
NAV_AH_LON,1518423250
NAV_DLL_ACT,0
NAV_DLL_AH_T,120.0
NAV_DLL_CHSK,0
NAV_DLL_CH_ALT,600.0
NAV_DLL_CH_LAT,-266072120
NAV_DLL_CH_LON,1518453890
NAV_DLL_CH_T,120.0
NAV_DLL_N,2
NAV_FORCE_VT,1
NAV_FT_DST,8.0
NAV_FT_FS,1
NAV_FT_RS,0.5
NAV_FW_ALTL_RAD,5.0
NAV_FW_ALT_RAD,1000.0
NAV_GPSF_LT,0.0
NAV_GPSF_P,0.0
NAV_GPSF_R,15.0
NAV_GPSF_TR,0.0
NAV_LOITER_RAD,50.0
NAV_MC_ALT_RAD,0.800000011920929
NAV_MIN_FT_HT,8.0
NAV_RCL_ACT,2
NAV_RCL_LT,120.0
NAV_TRAFF_AVOID,1
PLD_BTOUT,5.0
PLD_FAPPR_ALT,0.10000000149011612
PLD_HACC_RAD,0.20000000298023224
PLD_MAX_SRCH,3
PLD_SRCH_ALT,10.0
PLD_SRCH_TOUT,10.0
PWM_AUX_DIS1,-1
PWM_AUX_DIS2,-1
PWM_AUX_DIS3,-1
PWM_AUX_DIS4,-1
PWM_AUX_DIS5,-1
PWM_AUX_DIS6,-1
PWM_AUX_DIS7,-1
PWM_AUX_DIS8,-1
PWM_AUX_DISARMED,1500
PWM_AUX_FAIL1,-1
PWM_AUX_FAIL2,-1
PWM_AUX_FAIL3,-1
PWM_AUX_FAIL4,-1
PWM_AUX_FAIL5,-1
PWM_AUX_FAIL6,-1
PWM_AUX_FAIL7,-1
PWM_AUX_FAIL8,-1
PWM_AUX_MAX,2000
PWM_AUX_MAX1,-1
PWM_AUX_MAX2,-1
PWM_AUX_MAX3,-1
PWM_AUX_MAX4,-1
PWM_AUX_MAX5,-1
PWM_AUX_MAX6,-1
PWM_AUX_MAX7,-1
PWM_AUX_MAX8,-1
PWM_AUX_MIN,1000
PWM_AUX_MIN1,-1
PWM_AUX_MIN2,-1
PWM_AUX_MIN3,-1
PWM_AUX_MIN4,-1
PWM_AUX_MIN5,-1
PWM_AUX_MIN6,-1
PWM_AUX_MIN7,-1
PWM_AUX_MIN8,-1
PWM_AUX_RATE,50
PWM_AUX_REV1,0
PWM_AUX_REV2,0
PWM_AUX_REV3,0
PWM_AUX_REV4,0
PWM_AUX_REV5,0
PWM_AUX_REV6,0
PWM_AUX_REV7,0
PWM_AUX_REV8,0
PWM_AUX_TRIM1,0.0
PWM_AUX_TRIM2,0.0
PWM_AUX_TRIM3,0.0
PWM_AUX_TRIM4,0.0
PWM_AUX_TRIM5,0.0
PWM_AUX_TRIM6,0.0
PWM_AUX_TRIM7,0.0
PWM_AUX_TRIM8,0.0
PWM_DISARMED,1500
PWM_MAIN_DIS1,-1
PWM_MAIN_DIS2,-1
PWM_MAIN_DIS3,-1
PWM_MAIN_DIS4,-1
PWM_MAIN_DIS5,-1
PWM_MAIN_DIS6,-1
PWM_MAIN_DIS7,-1
PWM_MAIN_DIS8,-1
PWM_MAIN_FAIL1,-1
PWM_MAIN_FAIL2,-1
PWM_MAIN_FAIL3,-1
PWM_MAIN_FAIL4,-1
PWM_MAIN_FAIL5,-1
PWM_MAIN_FAIL6,-1
PWM_MAIN_FAIL7,-1
PWM_MAIN_FAIL8,-1
PWM_MAIN_MAX1,-1
PWM_MAIN_MAX2,-1
PWM_MAIN_MAX3,-1
PWM_MAIN_MAX4,-1
PWM_MAIN_MAX5,-1
PWM_MAIN_MAX6,-1
PWM_MAIN_MAX7,-1
PWM_MAIN_MAX8,-1
PWM_MAIN_MIN1,-1
PWM_MAIN_MIN2,-1
PWM_MAIN_MIN3,-1
PWM_MAIN_MIN4,-1
PWM_MAIN_MIN5,-1
PWM_MAIN_MIN6,-1
PWM_MAIN_MIN7,-1
PWM_MAIN_MIN8,-1
PWM_MAIN_REV1,0
PWM_MAIN_REV2,0
PWM_MAIN_REV3,0
PWM_MAIN_REV4,0
PWM_MAIN_REV5,0
PWM_MAIN_REV6,0
PWM_MAIN_REV7,0
PWM_MAIN_REV8,0
PWM_MAIN_TRIM1,0.0
PWM_MAIN_TRIM2,0.0
PWM_MAIN_TRIM3,0.0
PWM_MAIN_TRIM4,0.0
PWM_MAIN_TRIM5,0.0
PWM_MAIN_TRIM6,0.0
PWM_MAIN_TRIM7,0.0
PWM_MAIN_TRIM8,0.0
PWM_MAX,2000
PWM_MIN,1000
PWM_SBUS_MODE,0
RBCLW_SER_CFG,0
RC10_DZ,0.0
RC10_MAX,2000.0
RC10_MIN,1000.0
RC10_REV,1.0
RC10_TRIM,1500.0
RC11_DZ,0.0
RC11_MAX,2000.0
RC11_MIN,1000.0
RC11_REV,1.0
RC11_TRIM,1500.0
RC12_DZ,0.0
RC12_MAX,2000.0
RC12_MIN,1000.0
RC12_REV,1.0
RC12_TRIM,1500.0
RC13_DZ,0.0
RC13_MAX,2000.0
RC13_MIN,1000.0
RC13_REV,1.0
RC13_TRIM,1500.0
RC14_DZ,0.0
RC14_MAX,2000.0
RC14_MIN,1000.0
RC14_REV,1.0
RC14_TRIM,1500.0
RC15_DZ,0.0
RC15_MAX,2000.0
RC15_MIN,1000.0
RC15_REV,1.0
RC15_TRIM,1500.0
RC16_DZ,0.0
RC16_MAX,2000.0
RC16_MIN,1000.0
RC16_REV,1.0
RC16_TRIM,1500.0
RC17_DZ,0.0
RC17_MAX,2000.0
RC17_MIN,1000.0
RC17_REV,1.0
RC17_TRIM,1500.0
RC18_DZ,0.0
RC18_MAX,2000.0
RC18_MIN,1000.0
RC18_REV,1.0
RC18_TRIM,1500.0
RC1_DZ,10.0
RC1_MAX,2000.0
RC1_MIN,1000.0
RC1_REV,1.0
RC1_TRIM,1500.0
RC2_DZ,10.0
RC2_MAX,2000.0
RC2_MIN,1000.0
RC2_REV,1.0
RC2_TRIM,1500.0
RC3_DZ,10.0
RC3_MAX,2000.0
RC3_MIN,1000.0
RC3_REV,1.0
RC3_TRIM,1500.0
RC4_DZ,10.0
RC4_MAX,2000.0
RC4_MIN,1000.0
RC4_REV,1.0
RC4_TRIM,1500.0
RC5_DZ,10.0
RC5_MAX,2000.0
RC5_MIN,1000.0
RC5_REV,1.0
RC5_TRIM,1500.0
RC6_DZ,10.0
RC6_MAX,2000.0
RC6_MIN,1000.0
RC6_REV,1.0
RC6_TRIM,1500.0
RC7_DZ,10.0
RC7_MAX,2000.0
RC7_MIN,1000.0
RC7_REV,1.0
RC7_TRIM,1500.0
RC8_DZ,10.0
RC8_MAX,2000.0
RC8_MIN,1000.0
RC8_REV,1.0
RC8_TRIM,1500.0
RC9_DZ,0.0
RC9_MAX,2000.0
RC9_MIN,1000.0
RC9_REV,1.0
RC9_TRIM,1500.0
RC_ACRO_TH,0.5
RC_ARMSWITCH_TH,0.25
RC_ASSIST_TH,0.25
RC_AUTO_TH,0.75
RC_CHAN_CNT,0
RC_FAILS_THR,0
RC_FLT_CUTOFF,10.0
RC_FLT_SMP_RATE,50.0
RC_GEAR_TH,0.25
RC_KILLSWITCH_TH,0.25
RC_LOITER_TH,0.5
RC_MAN_TH,0.5
RC_MAP_ACRO_SW,0
RC_MAP_ARM_SW,0
RC_MAP_AUX1,4
RC_MAP_AUX2,1
RC_MAP_AUX3,0
RC_MAP_AUX4,0
RC_MAP_AUX5,0
RC_MAP_AUX6,0
RC_MAP_FAILSAFE,0
RC_MAP_FLAPS,2
RC_MAP_FLTMODE,0
RC_MAP_GEAR_SW,0
RC_MAP_KILL_SW,0
RC_MAP_LOITER_SW,0
RC_MAP_MAN_SW,0
RC_MAP_MODE_SW,0
RC_MAP_OFFB_SW,0
RC_MAP_PARAM1,5
RC_MAP_PARAM2,3
RC_MAP_PARAM3,7
RC_MAP_PITCH,0
RC_MAP_POSCTL_SW,0
RC_MAP_RATT_SW,0
RC_MAP_RETURN_SW,0
RC_MAP_ROLL,0
RC_MAP_STAB_SW,0
RC_MAP_THROTTLE,0
RC_MAP_TRANS_SW,0
RC_MAP_YAW,0
RC_OFFB_TH,0.5
RC_POSCTL_TH,0.5
RC_RATT_TH,0.5
RC_RETURN_TH,0.5
RC_RSSI_PWM_CHAN,0
RC_RSSI_PWM_MAX,1000
RC_RSSI_PWM_MIN,2000
RC_STAB_TH,0.5
RC_TRANS_TH,0.25
RTL_CONE_ANG,0
RTL_DESCEND_ALT,30.0
RTL_LAND_DELAY,-1.0
RTL_MIN_DIST,5.0
RTL_RETURN_ALT,60.0
RTL_TYPE,0
SDLOG_DIRS_MAX,0
SDLOG_MISSION,0
SDLOG_MODE,0
SDLOG_PROFILE,3
SDLOG_UTC_OFFSET,0
SENS_BARO_QNH,1013.25
SENS_BOARD_ROT,0
SENS_BOARD_X_OFF,-1.683549404144287
SENS_BOARD_Y_OFF,3.144094944000244
SENS_BOARD_Z_OFF,0.0
SENS_CM8JL65_CFG,0
SENS_DPRES_OFF,0.0
SENS_EN_BATT,0
SENS_EN_LL40LS,0
SENS_EN_MB12XX,0
SENS_EN_MPDT,0
SENS_EN_PGA460,0
SENS_EN_PMW3901,0
SENS_EN_PX4FLOW,0
SENS_EN_SF1XX,0
SENS_EN_THERMAL,-1
SENS_EN_TRANGER,0
SENS_FLOW_MAXHGT,3.0
SENS_FLOW_MAXR,2.5
SENS_FLOW_MINHGT,0.699999988079071
SENS_FLOW_ROT,6
SENS_LEDDAR1_CFG,0
SENS_SF0X_CFG,0
SENS_TFMINI_CFG,0
SENS_ULAND_CFG,0
SER_GPS1_BAUD,0
SER_TEL1_BAUD,57600
SYS_AUTOCONFIG,0
SYS_AUTOSTART,50002
SYS_CAL_ACCEL,0
SYS_CAL_BARO,0
SYS_CAL_GYRO,0
SYS_CAL_TDEL,24
SYS_CAL_TMAX,10
SYS_CAL_TMIN,5
SYS_HAS_BARO,0
SYS_HAS_MAG,0
SYS_HITL,0
SYS_PARAM_VER,1
SYS_RESTART_TYPE,0
SYS_STCK_EN,1
SYS_USE_IO,1
TC_A_ENABLE,0
TC_B_ENABLE,0
TC_G_ENABLE,0
TEL_BST_EN,0
TEL_FRSKY_CONFIG,0
TEL_HOTT_CONFIG,0
THR_MDL_FAC,0.0
TRIG_MODE,0
TRIM_PITCH,0.0
TRIM_ROLL,0.0
TRIM_YAW,0.0
UAVCAN_ENABLE,0
VT_B_DEC_MSS,2.0
VT_B_REV_DEL,0.0
